exp_name: AE_fashion_rotated
data:
  training:
    dataset: fashion
    root: ./dataset
    type: rotate
    download: true
    num_rotate: 100
    rotate_range: 180
    digit: 3
    batch_size: 50
    graph:
      num_nn: 10
      bs_nn: 2
      include_center: true
      replace: false
  test:
    dataset: fashion
    root: ./dataset
    type: rotate
    digit: 0
    download: true
    num_rotate: 50
    rotate_range: 180
    shift_range: 10
    batch_size: 50
model:
  arch: ae
  encoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'linear'
  decoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'sigmoid'
  x_dim: 784
  z_dim: 1
  kernel: 
    type: 'binary'
    lambda: 10
optimizer:
  lr: 0.001
training:
  num_epochs: 1001
