exp_name: AE_mnist_rotated
data:
  training:
    dataset: mnist
    root: './dataset'
    type: rotate
    num_rotate: 100
    rotate_range: 180
    digit: 5
    batch_size: 50
    graph: 
      include_center: True
      replace: False
      num_nn: 0
      bs_nn: 1
  test:
    dataset: mnist
    root: ./dataset
    type: rotate
    digit: 5
    download: true
    num_rotate: 100
    rotate_range: 180
    batch_size: 50
model:
  arch: ae
  encoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'linear'
  decoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'sigmoid'
  x_dim: 784
  z_dim: 2
optimizer:
  lr: 0.001
training:
  num_epochs: 1001
