exp_name: NRAEL_mnist_rotated
data:
  training:
    dataset: mnist
    root: './dataset'
    type: rotate
    num_rotate: 100
    rotate_range: 180
    digit: 5
    batch_size: 50
    graph: 
      include_center: True
      replace: False
      num_nn: 5
      bs_nn: 2
  test:
    dataset: mnist
    root: ./dataset
    type: rotate
    digit: 5
    download: true
    num_rotate: 50
    rotate_range: 180
    batch_size: 50
model:
  arch: nrael
  encoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'linear'
  decoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'sigmoid'
  x_dim: 784
  z_dim: 2
  kernel: 
    type: 'binary'
    lambda: 10
optimizer:
  lr: 0.001
training:
  num_epochs: 1001
device: cuda:0
logdir: results/NRAEL_mnist
